name: khushoo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  benchmark: ^0.3.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^2.0.0
  lottie: ^2.6.0
  cupertino_icons: ^1.0.5
  smooth_page_indicator: ^1.1.0
  semicircle_indicator: ^1.1.1
  curved_navigation_bar: ^1.0.3
  after_layout: ^1.2.0
  loading_indicator: ^3.1.1
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  geolocator: ^10.0.0
  geocoding: ^2.0.4
  location:
  loading_overlay: ^0.3.0
  awesome_notifications: ^0.7.4+1
  flutter_animate:
  intl: ^0.17.0
  http: ^1.1.0


flutter:
  uses-material-design: true
  fonts:
    - family: Mali
      fonts:
        - asset: fonts/Mali-Bold.ttf
        - asset: fonts/Mali-Light.ttf
        - asset: fonts/Mali-Regular.ttf


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/play_store_512.png"